<?php
/**
 * Schema Helper Functions
 * Convenience functions for adding structured data to specific page types
 */

require_once 'schema.php';

// Quick function to add schema to any page
function addPageSchema($pageType = 'default', $additionalData = []) {
    require_once 'schema.php';
    
    $breadcrumbs = isset($additionalData['breadcrumbs']) ? $additionalData['breadcrumbs'] : null;
    outputPageSchemas($pageType, $breadcrumbs);
}

// Specific helpers for different page types
function addHomePageSchema() {
    addPageSchema('home');
}

function addFAQPageSchema() {
    $breadcrumbs = [
        ["name" => "Home", "url" => APP_URL],
        ["name" => "FAQ", "url" => APP_URL . "/faq"]
    ];
    addPageSchema('faq', ['breadcrumbs' => $breadcrumbs]);
}

function addPrivacyPageSchema() {
    $breadcrumbs = [
        ["name" => "Home", "url" => APP_URL],
        ["name" => "Privacy Policy", "url" => APP_URL . "/privacy"]
    ];
    addPageSchema('default', ['breadcrumbs' => $breadcrumbs]);
}

function addTermsPageSchema() {
    $breadcrumbs = [
        ["name" => "Home", "url" => APP_URL],
        ["name" => "Terms of Service", "url" => APP_URL . "/terms"]
    ];
    addPageSchema('default', ['breadcrumbs' => $breadcrumbs]);
}

function addBlogPageSchema() {
    $breadcrumbs = [
        ["name" => "Home", "url" => APP_URL],
        ["name" => "Blog", "url" => APP_URL . "/blog"]
    ];
    addPageSchema('default', ['breadcrumbs' => $breadcrumbs]);
}

// Function to generate Article schema for blog posts
function generateArticleSchema($title, $description, $datePublished, $dateModified = null, $author = null) {
    $schema = [
        "@context" => "https://schema.org",
        "@type" => "Article",
        "headline" => $title,
        "description" => $description,
        "datePublished" => $datePublished,
        "dateModified" => $dateModified ?: $datePublished,
        "author" => [
            "@type" => "Organization",
            "name" => $author ?: APP_NAME,
            "url" => APP_URL
        ],
        "publisher" => [
            "@type" => "Organization",
            "name" => APP_NAME,
            "url" => APP_URL,
            "logo" => [
                "@type" => "ImageObject",
                "url" => APP_URL . "/assets/SecureNotes-Logo-lg.png"
            ]
        ],
        "mainEntityOfPage" => [
            "@type" => "WebPage",
            "@id" => APP_URL . $_SERVER['REQUEST_URI']
        ],
        "articleSection" => "Security",
        "wordCount" => strlen(strip_tags($description)),
        "keywords" => "security, encryption, privacy, secure notes"
    ];
    
    return json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
}

// Function to test schema validity (for development)
function validateSchema($schema) {
    $decoded = json_decode($schema, true);
    if (json_last_error() === JSON_ERROR_NONE) {
        return true;
    }
    return false;
}

// Function to output schema with error handling
function safeOutputSchema($schemaFunction, $params = []) {
    try {
        $schema = call_user_func_array($schemaFunction, $params);
        if (validateSchema($schema)) {
            outputSchemaScript($schema);
        } else {
            error_log("Invalid schema generated by: " . $schemaFunction);
        }
    } catch (Exception $e) {
        error_log("Schema generation error: " . $e->getMessage());
    }
}
?>